version: "3.9"
services:
  backend:
    container_name: backend
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    build:
      context: backend
      target: backend
    ports:
      - "${EXPRESS_LISTEN_PORT}:${EXPRESS_LISTEN_PORT}"
    # Watch and react to changes in local...
    volumes:
      #  backend-ts/src directory
      - type: bind
        source: ./backend/src
        target: /backend/src
      #  data directory
      - type: bind
        source: ./data
        target: /data

  frontend:
    container_name: frontend
    env_file:
      - .env
    build:
      context: frontend
      target: frontend
    ports:
      - "${REACT_APP_PORT}:3000"
    # Watch and react to changes in local...
    volumes:
      #  frontend/src directory
      - type: bind
        source: ./frontend/src
        target: /frontend/src
      #  data directory
      - type: bind
        source: ./data
        target: /data

  database:
    image: postgres:11.5-alpine
    container_name: database
    env_file:
      - .env
    build:
      context: data
      target: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # Create a managed docker volume to persist data if the container shuts down
      - db:/var/lib/postgresql/data
      # Watch and react to changes in local data directory
      - type: bind
        source: ./data
        target: /data

volumes:
  db:
